/home/l4d2server/log/console/l4d2server-console.log /home/l4d2server/log/perf-sampler.out {
    su l4d2server l4d2server
    daily
    maxsize 64M
    rotate 4
    missingok
    notifempty
    compress
    copytruncate
}
